[tool.commitizen]
version = "0.87.1"
tag_format = "v$version"
version_scheme = "semver"
bump_message = "bump: $current_version â†’ $new_version"
major_version_zero = true
gpg_sign = true
bump_map = { " " = "PATCH" }
